version: '3'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker-config/Dockerfile
    ports:
      - '14000:80'
    volumes:
      - .:/var/www/html

volumes:
  database_data:
